name=AS7331UVSensor
version=0.0.0
author=matt
maintainer=mumanchu <info@muman.ch>
sentence=AS7221 UVA/UVB/UVC Sensor Library (I2C)
paragraph=With UV Index and full range Irradiance calculations
category=Sensors
includes=AS7331UVSensor.h
url=https://github.com/mumanchu/AS7331UVSensor
architectures=stm32,esp32
