name=AS7331UVSensor
version=1.0.0
author=matt
maintainer=mumanchu <info@muman.ch>
sentence=AS7331 UVA/UVB/UVC Sensor Arduino Library (I2C)
paragraph=With UV Index, Automatic Gain Control and full range Irradiance calculations
category=Sensors
includes=AS7331UVSensor.h
url=https://github.com/mumanchu/AS7331UVSensor
architectures=*
